name: Run all tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install asxxxx
      run: |
        wget --no-verbose --content-disposition https://github.com/6502org/6502.org/blob/849e49b56798da9f81d5f0a6c0a40f84668a5d6d/public/tools/asm/asxv5p40_20211216.zip?raw=true
        unzip -q asxv5p40_20211216.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: sudo apt-get install srecord

    - name: Build the firmware (Attiny212 version)
      run: |
        make -C firmware/ MCU=t212
        cat firmware/redundant12v_t212_flash.lst
        cat firmware/redundant12v_t212_fuses.lst

    - name: Build the firmware (Attiny412 version)
      run: |
        make -C firmware/ MCU=t412
        cat firmware/redundant12v_t412_flash.lst
        cat firmware/redundant12v_t412_fuses.lst

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            firmware/redundant12v_*_flash.*
            firmware/redundant12v_*_fuses.*
